server:
  port: 8080
  servlet:
    context-path: /api

spring:
  mvc:
    static-path-pattern: /**

  resources:
    static-locations: file:.blog/static/

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    root: info
  file:
    path: .blog/data/log
