server:
  port: 8080
  servlet:
    context-path: /api
  max-http-header-size: 8192

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    root: info
  file:
    path: log
