GET http://localhost:8080/api/sort/all
Accept: application/json
Content-Type: application/json

###
GET http://localhost:8080/api/sort/1
Accept: application/json
Content-Type: application/json

###
POST http://localhost:8080/api/sort/add
Accept: application/json
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6Ijk3MTEwMSIsImV4cCI6MTU5Mjc5MTQ0OCwidXNlcm5hbWUiOiJhZG1pbiJ9.5-dJOx9KaLmR2GHXSBr8FBaWZMVxQme4UNAnj7D1d6A

{
  "name": "测试",
  "description": "测试"
}

###
PUT http://localhost:8080/api/sort/update
Accept: application/json
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6Ijk3MTEwMSIsImV4cCI6MTU5Mjc5MTQ0OCwidXNlcm5hbWUiOiJhZG1pbiJ9.5-dJOx9KaLmR2GHXSBr8FBaWZMVxQme4UNAnj7D1d6A

{
  "id": 5,
  "name": "测试2",
  "description": "测试2"
}

###
DELETE http://localhost:8080/api/sort/5
Accept: application/json
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6Ijk3MTEwMSIsImV4cCI6MTU5Mjc5MTQ0OCwidXNlcm5hbWUiOiJhZG1pbiJ9.5-dJOx9KaLmR2GHXSBr8FBaWZMVxQme4UNAnj7D1d6A
